import logoAudiobooksCom from "@/assets/logos/audiobooks-com.png";
import logoAudible from "@/assets/logos/audible-com.png";
import logoLibroFm from "@/assets/logos/libro-fm.png";
import logoEverand from "@/assets/logos/everand-com.png";
import logoKobo from "@/assets/logos/kobo-com.png";
import logoChirp from "@/assets/logos/chirpbooks-com.png";
import logoStorytel from "@/assets/logos/storytel-com.png";
import logoSpotify from "@/assets/logos/spotify-com.png";
import logoApple from "@/assets/logos/apple-com.png";
import logoAudiobookStore from "@/assets/logos/audiobookstore-com.png";
import logoDownpour from "@/assets/logos/downpour-com.png";
import logoLibby from "@/assets/logos/libbyapp-com.png";
import { AUDIOBOOKS_AFFILIATE_URL } from "@/lib/affiliate";

export type Service = {
  slug: string;
  name: string;
  company: string;
  url: string;
  domain: string;
  logo: string;
  affiliate: boolean;
  tagline: string;
  model: string;
  price: string;
  freeTrial: string;
  catalogue: string;
  keepBooks: string;
  offline: string;
  devices: string;
  drm: string;
  countries: string;
  rating: number;
  score: string;
  reviewedOn: string;
  reviewedOnISO: string;
  reviewer: string;
  summary: string;
  body: string[];
  pros: string[];
  cons: string[];
  bestFor: string[];
  verdict: string;
};

/** Audiobooks.com is the one partner we apply affiliate links to. */
export const AFFILIATE_URL = AUDIOBOOKS_AFFILIATE_URL;

export const services: Service[] = [
  {
    slug: "audiobooks-com",
    name: "Audiobooks.com",
    company: "Audiobooks.com (Storytel Group)",
    url: AFFILIATE_URL,
    domain: "audiobooks.com",
    logo: logoAudiobooksCom,
    affiliate: true,
    tagline: "One credit a month plus unlimited access to a large VIP listening library.",
    model: "Subscription — 1 credit/month + included VIP library",
    price: "$14.95 / month (US)",
    freeTrial: "30 days, 3 titles on most offers",
    catalogue: "400,000+ audiobooks, plus podcasts and summaries",
    keepBooks: "Yes — credit purchases stay in your library if you cancel",
    offline: "Yes, in the iOS and Android apps",
    devices: "iOS, Android, web player, CarPlay, Android Auto, Sonos",
    drm: "DRM-protected, app-only playback",
    countries: "US, Canada, UK, Australia and more",
    rating: 4.5,
    score: "4.5 / 5",
    reviewedOn: "2 September 2026",
    reviewedOnISO: "2026-09-02",
    reviewer: "Mara Chen",
    summary:
      "The most generous free trial in the category and a genuinely useful included library on top of the monthly credit.",
    body: [
      "Audiobooks.com sits between the two dominant models in this market. You get one credit a month for any title you want to keep, and on top of that an included VIP library you can listen to as much as you like while you subscribe. In practice that means the credit goes on the new release you actually care about and the included library covers the in-between weeks.",
      "The apps are the strongest part of the service for us. Playback speed is granular, sleep timers are sensible, and bookmarks sync quickly between phone and web. Car integration through CarPlay and Android Auto is reliable, which matters more than any feature list if most of your listening happens while driving.",
      "The trial is unusually long at 30 days with three titles on most offers, and this is the main reason we recommend starting here if you have never paid for audiobooks before. A month is long enough to learn whether you finish books in audio at all, which is the real question behind every subscription in this comparison.",
      "Two honest limitations. Exclusive originals are thinner than Audible's, and playback is app-only — there are no downloadable files you can move to a device of your choice the way Libro.fm and Downpour allow.",
    ],
    pros: [
      "30-day trial is the longest of the major paid services",
      "Monthly credit plus an included listening library",
      "Credit purchases are yours to keep after cancelling",
      "Strong car and smart-speaker support",
    ],
    cons: [
      "Fewer exclusive originals than Audible",
      "No DRM-free downloads",
      "Podcast and summary content pads the catalogue count",
    ],
    bestFor: [
      "First-time audiobook subscribers",
      "Listeners who want one keeper plus casual listening",
      "Commuters and drivers",
    ],
    verdict:
      "Our default recommendation for a first subscription: the long trial and the combined credit-plus-library model make it hard to lose money finding out whether audiobooks suit you.",
  },
  {
    slug: "audible",
    name: "Audible",
    company: "Amazon",
    url: "https://www.audible.com/",
    domain: "audible.com",
    logo: logoAudible,
    affiliate: false,
    tagline: "The biggest catalogue and the deepest bench of exclusive originals.",
    model: "Subscription — 1 credit/month + Plus Catalog",
    price: "$14.95 / month (Premium Plus, US)",
    freeTrial: "30 days, 1 credit",
    catalogue: "Largest in the market, with heavy exclusives",
    keepBooks: "Yes — credit purchases are kept",
    offline: "Yes",
    devices: "iOS, Android, Kindle, Fire, Alexa, web",
    drm: "DRM-protected, Audible apps only",
    countries: "Most major markets",
    rating: 4.5,
    score: "4.5 / 5",
    reviewedOn: "28 August 2026",
    reviewedOnISO: "2026-08-28",
    reviewer: "Jonah Reyes",
    summary:
      "Unmatched for breadth and exclusives, and the hardest service to leave once your library lives inside it.",
    body: [
      "If a title exists in audio, Audible almost certainly has it. That breadth is the whole argument, and for heavy listeners chasing specific narrators or series it settles the question.",
      "The Plus Catalog has grown into a real perk rather than a bargain bin, and Alexa and Kindle integration is smoother than anything a competitor can offer. Whispersync between ebook and audiobook still feels like the single best feature in the category.",
      "The catch is lock-in. Your purchases are readable only in Amazon's apps, so leaving means leaving your library behind. We also find title-level pricing outside credits to be the least attractive of the major stores.",
    ],
    pros: ["Biggest catalogue anywhere", "Best-in-class exclusives and originals", "Whispersync with Kindle editions"],
    cons: ["Heavy platform lock-in", "Expensive à la carte pricing", "No support for independent bookshops"],
    bestFor: ["Heavy listeners", "Series and narrator completists", "Kindle and Alexa households"],
    verdict:
      "The safest choice for catalogue depth, and the one we would think hardest about before committing a large library to.",
  },
  {
    slug: "libro-fm",
    name: "Libro.fm",
    company: "Libro.fm",
    url: "https://libro.fm/",
    domain: "libro.fm",
    logo: logoLibroFm,
    affiliate: false,
    tagline: "Same credits, same catalogue — but your money supports an independent bookshop.",
    model: "Subscription — 1 credit/month, or à la carte",
    price: "$14.99 / month (US)",
    freeTrial: "First month, 1 credit",
    catalogue: "500,000+ titles from major and indie publishers",
    keepBooks: "Yes, as DRM-free downloads",
    offline: "Yes, including MP3 files you own",
    devices: "iOS, Android, web, any MP3 player",
    drm: "DRM-free",
    countries: "US and Canada primarily",
    rating: 4.5,
    score: "4.5 / 5",
    reviewedOn: "24 August 2026",
    reviewedOnISO: "2026-08-24",
    reviewer: "Priya Raman",
    summary:
      "The ethical pick, and the only major subscription where the files are genuinely yours.",
    body: [
      "Libro.fm matches the big services on price and on most of the catalogue, then splits the revenue with an independent bookshop you choose at signup. If that matters to you, the decision is easy.",
      "DRM-free downloads are the practical advantage. You can archive an MP3 copy, play it in any app, and keep it whatever happens to your account — which is not true of Audible or Audiobooks.com.",
      "The apps are competent rather than luxurious, and there are no exclusives to speak of. Availability outside North America is also patchier than the global players.",
    ],
    pros: ["DRM-free files you truly own", "Supports independent bookshops", "Frequent à la carte sales"],
    cons: ["No exclusive originals", "Apps feel plainer than rivals", "Limited outside North America"],
    bestFor: ["Listeners who want to own files", "Indie bookshop supporters", "Archivists"],
    verdict: "The service we recommend to anyone who resents renting their library.",
  },
  {
    slug: "everand",
    name: "Everand",
    company: "Scribd",
    url: "https://www.everand.com/",
    domain: "everand.com",
    logo: logoEverand,
    affiliate: false,
    tagline: "One fee for audiobooks, ebooks, magazines and sheet music — with soft limits.",
    model: "Subscription — all-you-can-read with throttling",
    price: "From $11.99 / month",
    freeTrial: "30 days",
    catalogue: "Very large mixed library of books, magazines and documents",
    keepBooks: "No — access ends with the subscription",
    offline: "Yes, while subscribed",
    devices: "iOS, Android, web",
    drm: "DRM-protected",
    countries: "Worldwide",
    rating: 4,
    score: "4 / 5",
    reviewedOn: "20 August 2026",
    reviewedOnISO: "2026-08-20",
    reviewer: "Mara Chen",
    summary: "Best value per hour if you read widely and can live with unpredictable availability.",
    body: [
      "Everand is the buffet option. For one monthly fee you get audiobooks alongside ebooks, magazines and a sprawling document library, and for mixed readers the value per hour is the best here.",
      "The complication is throttling. Heavy listeners eventually see popular titles hidden until the next cycle, which the service does not explain clearly enough. Treat availability as a moving target, not a catalogue.",
      "Nothing is kept. Cancel and the shelf empties, which makes it a poor fit for anyone building a permanent library.",
    ],
    pros: ["Audiobooks plus ebooks and magazines in one fee", "Cheapest entry price of the big subscriptions", "Excellent for wide, casual reading"],
    cons: ["Availability throttling for heavy users", "Nothing is kept after cancelling", "Newest releases often missing"],
    bestFor: ["Mixed readers", "Value hunters", "Non-fiction browsers"],
    verdict: "Great value while you subscribe, with no library to show for it afterwards.",
  },
  {
    slug: "chirp",
    name: "Chirp",
    company: "BookBub",
    url: "https://www.chirpbooks.com/",
    domain: "chirpbooks.com",
    logo: logoChirp,
    affiliate: false,
    tagline: "Daily discounted audiobooks with no subscription at all.",
    model: "À la carte — limited-time deals",
    price: "No monthly fee; deals often $0.99–$5.99",
    freeTrial: "Not applicable",
    catalogue: "Rotating deals across most major publishers",
    keepBooks: "Yes — purchases are permanent",
    offline: "Yes",
    devices: "iOS, Android, web player",
    drm: "DRM-protected, Chirp app",
    countries: "US primarily, some titles elsewhere",
    rating: 4,
    score: "4 / 5",
    reviewedOn: "18 August 2026",
    reviewedOnISO: "2026-08-18",
    reviewer: "Jonah Reyes",
    summary: "The best way to build a library cheaply if you are patient about what you read next.",
    body: [
      "Chirp sells time-limited audiobook deals and nothing else. There is no membership, no credit to burn before it expires, and prices on backlist titles regularly beat every subscription in this list on a per-book basis.",
      "The daily email is the product. Deals rotate, so your reading order is dictated by what happens to be cheap, which suits browsers and frustrates anyone with a fixed list.",
      "Playback lives in Chirp's own app, which is basic but stable.",
    ],
    pros: ["No subscription required", "Genuinely low prices on backlist", "Purchases are permanent"],
    cons: ["You read what is on sale", "Basic app", "Few new releases"],
    bestFor: ["Bargain hunters", "Backlist readers", "People who hate subscriptions"],
    verdict: "A perfect companion to a subscription rather than a replacement for one.",
  },
  {
    slug: "kobo-audiobooks",
    name: "Kobo Audiobooks",
    company: "Rakuten Kobo",
    url: "https://www.kobo.com/audiobooks",
    domain: "kobo.com",
    logo: logoKobo,
    affiliate: false,
    tagline: "A credible Amazon alternative for people already reading on a Kobo.",
    model: "Subscription credits or à la carte",
    price: "$12.99 / month for 1 credit (US)",
    freeTrial: "30 days",
    catalogue: "Large, close to the major stores",
    keepBooks: "Yes",
    offline: "Yes",
    devices: "iOS, Android, Kobo devices, web",
    drm: "DRM-protected",
    countries: "Wide international coverage",
    rating: 4,
    score: "4 / 5",
    reviewedOn: "15 August 2026",
    reviewedOnISO: "2026-08-15",
    reviewer: "Priya Raman",
    summary: "Ebooks and audiobooks in one account, and the friendliest big store outside the US.",
    body: [
      "For readers who already own a Kobo e-reader, keeping audio in the same account is a real convenience, and Kobo's international coverage beats most rivals.",
      "Credit pricing is slightly cheaper than Audible and Audiobooks.com, but the audio catalogue is thinner in places and the app is the weakest part of the experience.",
      "There are no originals, and discovery inside the store is poor compared with the editorial curation elsewhere.",
    ],
    pros: ["Cheaper monthly credit", "Great international availability", "One account for ebooks and audio"],
    cons: ["App is clunky", "Thinner audio catalogue", "Weak discovery"],
    bestFor: ["Kobo device owners", "Listeners outside the US", "Amazon avoiders"],
    verdict: "A sensible non-Amazon default, especially outside North America.",
  },
  {
    slug: "spotify-audiobooks",
    name: "Spotify Audiobooks",
    company: "Spotify",
    url: "https://www.spotify.com/us/audiobooks/",
    domain: "spotify.com",
    logo: logoSpotify,
    affiliate: false,
    tagline: "Fifteen included listening hours a month inside an app you already pay for.",
    model: "Included with Premium — 15 hours/month",
    price: "From $11.99 / month (Premium)",
    freeTrial: "Premium trial where available",
    catalogue: "350,000+ included titles",
    keepBooks: "No, unless bought separately",
    offline: "Yes",
    devices: "Everything Spotify runs on",
    drm: "DRM-protected",
    countries: "Growing list of markets",
    rating: 3.5,
    score: "3.5 / 5",
    reviewedOn: "12 August 2026",
    reviewedOnISO: "2026-08-12",
    reviewer: "Mara Chen",
    summary: "Effectively free if you already subscribe, and frustrating if audiobooks become your main habit.",
    body: [
      "Fifteen hours covers roughly one and a half average audiobooks a month. For occasional listeners that is plenty and costs nothing extra.",
      "The listening experience is the weak point. Spotify's player was built for music, and chapter navigation, bookmarks and speed controls are all a step behind dedicated apps.",
      "The hour cap arrives without ceremony, and top-ups are poor value. Anyone finishing three books a month should subscribe elsewhere.",
    ],
    pros: ["No extra cost for Premium subscribers", "Large included catalogue", "Works on every device you already use"],
    cons: ["15-hour monthly cap", "Player is weak for long-form audio", "Nothing kept"],
    bestFor: ["Occasional listeners", "Existing Premium subscribers", "Trying audiobooks for free"],
    verdict: "A fine way to start, and the first thing you will outgrow.",
  },
  {
    slug: "storytel",
    name: "Storytel",
    company: "Storytel Group",
    url: "https://www.storytel.com/",
    domain: "storytel.com",
    logo: logoStorytel,
    affiliate: false,
    tagline: "The strongest unlimited service outside English-speaking markets.",
    model: "Subscription — unlimited listening tiers",
    price: "Varies by country",
    freeTrial: "Typically 14–30 days",
    catalogue: "Very large, with deep non-English catalogues",
    keepBooks: "No",
    offline: "Yes",
    devices: "iOS, Android, web, car",
    drm: "DRM-protected",
    countries: "Europe, Middle East, Asia, Latin America",
    rating: 4,
    score: "4 / 5",
    reviewedOn: "8 August 2026",
    reviewedOnISO: "2026-08-08",
    reviewer: "Jonah Reyes",
    summary: "If you listen in Swedish, Arabic, Hindi, Dutch or Turkish, this is usually the best option available.",
    body: [
      "Storytel's unlimited tiers are excellent value and its non-English catalogues are the deepest we have tested, including strong local originals.",
      "Some markets throttle heavy listeners on the cheapest tier, so read the plan detail before assuming unlimited means unlimited.",
      "It is not sold in the US, which is the single biggest reason English-language readers overlook it.",
    ],
    pros: ["True unlimited listening on most tiers", "Outstanding non-English catalogue", "Strong local originals"],
    cons: ["Not available in the US", "Some tiers throttle heavy use", "Nothing kept after cancelling"],
    bestFor: ["Non-English listeners", "Heavy listeners in Europe and Asia", "Family plan households"],
    verdict: "The clear pick in the markets where it operates.",
  },
  {
    slug: "apple-books-audiobooks",
    name: "Apple Books Audiobooks",
    company: "Apple",
    url: "https://www.apple.com/apple-books/",
    domain: "apple.com",
    logo: logoApple,
    affiliate: false,
    tagline: "No subscription, no friction — just buy the book on the device you already carry.",
    model: "À la carte purchases",
    price: "Per title, typically $9.99–$29.99",
    freeTrial: "Not applicable",
    catalogue: "Large, plus AI-narrated indie titles",
    keepBooks: "Yes",
    offline: "Yes",
    devices: "iPhone, iPad, Mac, CarPlay, Apple Watch",
    drm: "DRM-protected, Apple ecosystem only",
    countries: "Worldwide",
    rating: 3.5,
    score: "3.5 / 5",
    reviewedOn: "5 August 2026",
    reviewedOnISO: "2026-08-05",
    reviewer: "Priya Raman",
    summary: "The most frictionless purchase in audiobooks, at the least competitive price.",
    body: [
      "Buying is one tap and playback across iPhone, Mac, Watch and CarPlay is seamless. For Apple households the convenience is real.",
      "You pay for it. Without credits or subscription discounts, full-price titles cost noticeably more than the same book bought with a credit elsewhere.",
      "Nothing you buy leaves the Apple ecosystem, and the AI-narrated titles are variable in quality.",
    ],
    pros: ["Effortless on Apple devices", "No subscription commitment", "Excellent CarPlay and Watch handoff"],
    cons: ["Most expensive per book", "Apple devices only", "Uneven AI narration"],
    bestFor: ["Apple-only households", "Occasional buyers", "Gift purchases"],
    verdict: "Convenient and costly — fine for a few books a year, poor value beyond that.",
  },
  {
    slug: "downpour",
    name: "Downpour",
    company: "Blackstone Publishing",
    url: "https://www.downpour.com/",
    domain: "downpour.com",
    logo: logoDownpour,
    affiliate: false,
    tagline: "DRM-free purchases and the rare option to rent an audiobook.",
    model: "À la carte, credits, or rentals",
    price: "$12.99 / month for 1 credit; rentals from about $5",
    freeTrial: "30 days",
    catalogue: "Strong Blackstone catalogue plus wide licensing",
    keepBooks: "Yes, DRM-free",
    offline: "Yes, MP3 downloads",
    devices: "iOS, Android, any MP3 player",
    drm: "DRM-free",
    countries: "US primarily",
    rating: 3.5,
    score: "3.5 / 5",
    reviewedOn: "1 August 2026",
    reviewedOnISO: "2026-08-01",
    reviewer: "Mara Chen",
    summary: "Rentals make expensive long books affordable, and the files are DRM-free.",
    body: [
      "Renting a 30-hour history for a few dollars is a genuinely useful option that almost nobody else offers, and purchases arrive DRM-free.",
      "The website looks a decade old and browsing is a chore, but the download workflow is dependable.",
      "Availability is mostly US-only and rental windows are short, so plan your listening.",
    ],
    pros: ["Audiobook rentals", "DRM-free downloads", "Deep Blackstone catalogue"],
    cons: ["Dated website", "Mostly US-only", "Short rental windows"],
    bestFor: ["One-off long listens", "DRM-free buyers", "Blackstone narration fans"],
    verdict: "Worth bookmarking for rentals even if you subscribe elsewhere.",
  },
  {
    slug: "audiobookstore-com",
    name: "AudiobookSTORE.com",
    company: "AudiobookSTORE.com",
    url: "https://www.audiobookstore.com/",
    domain: "audiobookstore.com",
    logo: logoAudiobookStore,
    affiliate: false,
    tagline: "An independent store with aggressive weekly sales and a free book on signup.",
    model: "À la carte and club credits",
    price: "Frequent sales; club credit around $12.99",
    freeTrial: "Free audiobook on signup",
    catalogue: "Mid-sized, mainstream focused",
    keepBooks: "Yes",
    offline: "Yes",
    devices: "iOS, Android, web",
    drm: "DRM-protected",
    countries: "US and international",
    rating: 3,
    score: "3 / 5",
    reviewedOn: "28 July 2026",
    reviewedOnISO: "2026-07-28",
    reviewer: "Jonah Reyes",
    summary: "Prices are the draw; the apps and catalogue are the compromise.",
    body: [
      "Weekly sales here can undercut every subscription on a per-title basis, and the free signup book is a real one rather than a sample.",
      "The catalogue skips a lot of literary and translated work, and the apps are the most basic of the twelve services we track.",
      "Fine as a second shop for bestsellers, weak as your only one.",
    ],
    pros: ["Very cheap sale pricing", "Free book on signup", "No subscription needed"],
    cons: ["Limited catalogue", "Basic apps", "Cluttered store"],
    bestFor: ["Bestseller readers", "Deal hunters", "Second-shop buyers"],
    verdict: "Useful for a cheap bestseller, not a primary library.",
  },
  {
    slug: "libby",
    name: "Libby",
    company: "OverDrive",
    url: "https://libbyapp.com/",
    domain: "libbyapp.com",
    logo: logoLibby,
    affiliate: false,
    tagline: "Free audiobooks through your public library — if you can wait for the hold.",
    model: "Free with a library card",
    price: "Free",
    freeTrial: "Not applicable",
    catalogue: "Depends entirely on your library's licences",
    keepBooks: "No — loans expire",
    offline: "Yes, during the loan",
    devices: "iOS, Android, web, Sonos, CarPlay",
    drm: "DRM-protected library loans",
    countries: "Anywhere with participating libraries",
    rating: 4.5,
    score: "4.5 / 5",
    reviewedOn: "24 July 2026",
    reviewedOnISO: "2026-07-24",
    reviewer: "Priya Raman",
    summary: "The best value in audiobooks, full stop — the price of admission is patience.",
    body: [
      "Libby turns a library card into a full audiobook service with an app that is better designed than most paid competitors. Loans, holds, speed controls and car playback all work well.",
      "Popular titles carry waiting lists that can run for months, and small library systems have thin audio collections.",
      "We recommend everyone install Libby regardless of what they subscribe to. It costs nothing and it will cover a meaningful share of your listening.",
    ],
    pros: ["Completely free", "Excellent app", "Supports public libraries"],
    cons: ["Long holds on popular titles", "Catalogue varies by library", "Loans expire"],
    bestFor: ["Every listener, as a supplement", "Patient readers", "Budget listening"],
    verdict: "Install it even if you pay for something else — nothing else offers this value.",
  },
];

export function getService(slug: string) {
  return services.find((s) => s.slug === slug);
}

export const comparisonGroups: { title: string; blurb: string; slugs: string[] }[] = [
  {
    title: "Subscription services",
    blurb: "Monthly fee, credits or unlimited listening, nothing kept unless the plan says so.",
    slugs: ["audiobooks-com", "audible", "libro-fm", "everand", "kobo-audiobooks", "storytel", "spotify-audiobooks"],
  },
  {
    title: "Buy per book",
    blurb: "No commitment. You pay once and the audiobook stays yours.",
    slugs: ["chirp", "apple-books-audiobooks", "downpour", "audiobookstore-com"],
  },
  {
    title: "Free listening",
    blurb: "No payment at all, at the cost of waiting lists and limits.",
    slugs: ["libby"],
  },
];

export const headToHeads: { slugs: [string, string]; question: string; answer: string }[] = [
  {
    slugs: ["audiobooks-com", "audible"],
    question: "Audiobooks.com or Audible?",
    answer:
      "Same monthly price. Audible wins on catalogue size and exclusives; Audiobooks.com wins on trial length and on the included VIP library you can dip into between credits. If you are unsure whether you will stick with audiobooks, start with the longer trial.",
  },
  {
    slugs: ["libro-fm", "audible"],
    question: "Libro.fm or Audible?",
    answer:
      "Almost identical cost. Libro.fm gives you DRM-free files and splits revenue with an independent bookshop; Audible gives you a bigger catalogue and Kindle sync. Ownership versus breadth.",
  },
  {
    slugs: ["everand", "storytel"],
    question: "Everand or Storytel?",
    answer:
      "Both are all-you-can-listen with soft limits. Everand adds ebooks and magazines and is available in the US; Storytel has far better non-English catalogues and is not sold in the US.",
  },
  {
    slugs: ["chirp", "libby"],
    question: "Chirp or Libby?",
    answer:
      "Libby is free but you wait; Chirp is cheap and instant. Most listeners we know use both — Libby for the queue, Chirp for the book they want tonight.",
  },
];
