/**
 * Generates public/sitemap.xml from the route data.
 *
 * This exists because the sitemap was previously hand-maintained and drifted:
 * it advertised sixteen review URLs that had been renamed, so every review link
 * we submitted to Google was a 404. Deriving the file from the source data means
 * that cannot happen again.
 *
 * Slugs are read with regexes rather than by importing the modules, because the
 * data files import PNG assets and path aliases that plain Node cannot resolve.
 * The expected-count assertions below are what stop a silent regex failure from
 * quietly shipping an empty sitemap.
 *
 * Run automatically before every build (see the `prebuild` script).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://www.pageturn.cloud";

/** Pulls every `slug: "..."` literal out of a data module. */
function slugsFrom(relativePath, { min }) {
  const source = readFileSync(join(root, relativePath), "utf8");
  const slugs = [...source.matchAll(/^\s{2,}slug: "([a-z0-9-]+)",$/gm)].map((m) => m[1]);
  const unique = [...new Set(slugs)];

  if (unique.length < min) {
    throw new Error(
      `generate-sitemap: expected at least ${min} slugs in ${relativePath}, found ${unique.length}. ` +
        `The data shape probably changed — fix this script rather than shipping a truncated sitemap.`,
    );
  }
  return unique;
}

const reviewSlugs = slugsFrom("src/lib/reviews.ts", { min: 10 });
const serviceSlugs = slugsFrom("src/lib/services.ts", { min: 10 });
const roundupSlugs = slugsFrom("src/lib/roundups.ts", { min: 8 });
const versusSlugs = slugsFrom("src/lib/versus.ts", { min: 5 });
const guideSlugs = slugsFrom("src/lib/guides.ts", { min: 4 });

const today = new Date().toISOString().slice(0, 10);

/** @type {{loc: string, changefreq: string, priority: string}[]} */
const urls = [
  // Hubs and evergreen pages.
  { loc: "/", changefreq: "daily", priority: "1.0" },
  { loc: "/reviews", changefreq: "daily", priority: "0.9" },
  { loc: "/best", changefreq: "weekly", priority: "0.9" },
  { loc: "/services", changefreq: "weekly", priority: "0.9" },
  { loc: "/compare", changefreq: "weekly", priority: "0.9" },
  { loc: "/guides", changefreq: "weekly", priority: "0.8" },
  { loc: "/about", changefreq: "monthly", priority: "0.6" },
  { loc: "/contact", changefreq: "monthly", priority: "0.5" },
  { loc: "/disclosure", changefreq: "monthly", priority: "0.5" },
  { loc: "/privacy", changefreq: "yearly", priority: "0.3" },
  { loc: "/terms", changefreq: "yearly", priority: "0.3" },

  // Commercial pages get the highest article priority — they are the ones we
  // most want recrawled when prices change.
  ...roundupSlugs.map((slug) => ({
    loc: `/best/${slug}`,
    changefreq: "weekly",
    priority: "0.9",
  })),
  ...versusSlugs.map((slug) => ({
    loc: `/compare/${slug}`,
    changefreq: "weekly",
    priority: "0.9",
  })),
  ...serviceSlugs.map((slug) => ({
    loc: `/services/${slug}`,
    changefreq: "weekly",
    priority: "0.8",
  })),
  ...guideSlugs.map((slug) => ({
    loc: `/guides/${slug}`,
    changefreq: "monthly",
    priority: "0.7",
  })),
  ...reviewSlugs.map((slug) => ({
    loc: `/reviews/${slug}`,
    changefreq: "monthly",
    priority: "0.7",
  })),
];

const body = urls
  .map(
    ({ loc, changefreq, priority }) =>
      `  <url>\n` +
      `    <loc>${SITE_URL}${loc}</loc>\n` +
      `    <lastmod>${today}</lastmod>\n` +
      `    <changefreq>${changefreq}</changefreq>\n` +
      `    <priority>${priority}</priority>\n` +
      `  </url>`,
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(join(root, "public/sitemap.xml"), xml, "utf8");

console.log(
  `generate-sitemap: wrote ${urls.length} URLs ` +
    `(${reviewSlugs.length} reviews, ${serviceSlugs.length} services, ` +
    `${roundupSlugs.length} roundups, ${versusSlugs.length} comparisons, ${guideSlugs.length} guides)`,
);
