/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BestIndexRouteImport } from './routes/best.index'
import { Route as BestSlugRouteImport } from './routes/best.$slug'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BestIndexRoute = BestIndexRouteImport.update({
  id: '/best/',
  path: '/best/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSlugRoute = BestSlugRouteImport.update({
  id: '/best/$slug',
  path: '/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/best/': typeof BestIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/best': typeof BestIndexRoute
  '/compare': typeof CompareIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/disclosure': typeof DisclosureRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/best/$slug': typeof BestSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/best/': typeof BestIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/privacy'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/services/$slug'
    | '/best/'
    | '/compare/'
    | '/guides/'
    | '/reviews/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/privacy'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/services/$slug'
    | '/best'
    | '/compare'
    | '/guides'
    | '/reviews'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/disclosure'
    | '/privacy'
    | '/terms'
    | '/best/$slug'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/reviews/$slug'
    | '/services/$slug'
    | '/best/'
    | '/compare/'
    | '/guides/'
    | '/reviews/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DisclosureRoute: typeof DisclosureRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BestSlugRoute: typeof BestSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BestIndexRoute: typeof BestIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/': {
      id: '/best/'
      path: '/best'
      fullPath: '/best/'
      preLoaderRoute: typeof BestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best/$slug': {
      id: '/best/$slug'
      path: '/best/$slug'
      fullPath: '/best/$slug'
      preLoaderRoute: typeof BestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DisclosureRoute: DisclosureRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BestSlugRoute: BestSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BestIndexRoute: BestIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
